# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657fb378248c3fa6e59fbeff8892718d7c1c84aa06e93904b4633cd75eaebbae0f65b5f4447038c32855a2ff6025296c62d40b43d4587ba0922e9d1e86a30157

test:
  secret_key_base: b7337d2f21e29198bf52fecf881278cbaf6491cd12eec96825e0dfc46a481e6e3d6d183e3b7040be8218a9aba91c608a6d159f681a1f7a2cee18cd2808a4eb97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
